name: CI & CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx format:check

      - run: npx nx affected -t lint test build

  deploy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      # - name: Cache directory
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-dot-firebase
      #   with:
      #     path: .firebase
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.firebase/**') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WHAT_DOES_THE_DUDE_SAY }}
          channelId: live
          projectId: what-does-the-dude-say
